[package]
name = "strand-cam-offline-kalmanize"
version = "0.9.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.5", features = ["release_max_level_debug"] }
env_logger = "0.8"
structopt = "0.3.13"
parking_lot = "0.11"
crossbeam-channel = "0.5"
csv = "1.1"
chrono = "0.4.6"
serde = {version="^1.0", features=["derive"]}
serde_derive = "1.0.79"
serde_json = "1.0.29"
serde_yaml = "^0.8"
toml = "0.5"
nalgebra = {version="0.26", features=["serde-serialize"]}
ncollide3d = "0.29"
alga = "0.9"
configure = "0.1.1"
itertools = "0.8"
lazy_static = "1.4.0"
hyper = "0.14"
futures = "0.3"
tokio = {version="1.0.1", default-features=false, features=["macros"]}
includedir = { version = "0.5", optional = true }
tempdir = "^0.3"
phf = { version = "0.7.23", optional = true }
anyhow = "1.0"

datetime-conversion = {path="../datetime-conversion"}
mvg = {path="../mvg"}
flydra-mvg = {path="../flydra-mvg"}
http-video-streaming-types = {path="../http-video-streaming/http-video-streaming-types"}
flydra-types = {path="../flydra-types"}
tracking = {path="../tracking"}
groupby = {path="../groupby"}
pretty-print-nalgebra = {git="https://github.com/strawlab/pretty-print-nalgebra", rev="142f427bfe9d2230b0dae0a5f7527703f43ae899"}
withkey = {path="../withkey"}
crossbeam-ok = {path="../crossbeam-ok"}
strand-cam-csv-config-types = {path="../strand-cam-csv-config-types"}
strand-cam-pseudo-cal = {path="../strand-cam-pseudo-cal"}
flydra2 = {path="../flydra2", default-features = false, features=["flat-3d", "bundle_files"]}
braidz-parser = {path="../braidz-parser"}
zip-or-dir = {path="../zip-or-dir"}
braid-offline = {path="../braid-offline", default-features = false, features=["flat-3d"]}
