[package]
name = "strand-cam"
version = "0.9.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
build = "build.rs"
edition = "2018"

[lib]
path = "src/strand-cam.rs"

[dependencies]
jemallocator = {version="0.3", optional=true}
async-change-tracker = "0.3"
bui-backend-types = "0.8"
bui-backend = {version="0.11", default-features = false}
qrcodegen = "1.4"
log = { version = "0.4.5", features = ["release_max_level_debug"] }
ctrlc = { version = "3.1.3", features = ["termination"] }
stream-cancel = "0.8"
csv = {version="1.1", optional=true}
libflate = {version="1.0", optional=true}
env-tracing-logger = {path="../env-tracing-logger"}

includedir = { version = "0.6", optional = true }
phf = { version = "0.8", optional = true }
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.29"
serde_yaml = "0.8.4"
webbrowser = "0.5.2"
clap = "2.32.0"
preferences = {git="https://github.com/Eh2406/preferences-rs", rev="4f426cf52da97d3b8914e10d4492f953d4304238"}
app_dirs = "1.2"
failure = "0.1.6"
anyhow = "1.0"
thiserror = "1.0"
parking_lot = "0.11"
crossbeam-channel = "0.5"
thread-control = "0.1.2"
ipp-sys = {version="0.4.4", optional=true}
ci2 = { path = "../ci2" }
ci2-async = { path = "../ci2-async" }
ci2-types = { path = "../ci2/ci2-types" }
ci2-dc1394 = { path = "../ci2-dc1394", optional = true }
ci2-flycap2 = { path = "../ci2-flycap2", optional = true }
ci2-pyloncxx = { path = "../ci2-pyloncxx", optional = true }
# ci2-aravis = { path = "../ci2-aravis", optional = true }
ci2-remote-control = { path = "../ci2-remote-control" }
machine-vision-formats = { path = "../machine-vision-formats" }
timestamped-frame = { path = "../timestamped-frame" }
basic-frame = { path = "../basic-frame" }
fmf = {path = "../fmf"}
ufmf = {path = "../ufmf"}
chrono = { version = "0.4.6", features = ["serde"] }
convert-image = {path = "../convert-image"}
hyper = {version="0.14", features=["client","http1"]}
hyper-tls = "0.5"
futures = "0.3"
tokio = {version="1.0.1", default-features=false, features=["rt","rt-multi-thread","time","sync"]}
tokio-util = {version = "0.6", features=["codec"]}
dotenv = "0.15.0"
strand-cam-storetype = {path = "../strand-cam-storetype"}
image-tracker = {path = "../image-tracker", default-features = false, optional=true}
image-tracker-types = {path = "../image-tracker/image-tracker-types", default-features = false}
im-pt-detect-config = {path = "../image-tracker/im-pt-detect-config"}
datetime-conversion = {path = "../datetime-conversion"}
http-video-streaming-types = {path = "../http-video-streaming/http-video-streaming-types"}
http-video-streaming = {path = "../http-video-streaming"}
semver = { version = "0.11.0", features = ["serde"] }
shellexpand = "2"
camtrig = {path="../camtrig", optional=true}
camtrig-comms = {path="../camtrig-comms", optional=true}
flydra-types = {path="../flydra-types", features=["with-dns"]}
flydra2 = {path="../flydra2", default-features = false, optional=true}
mvg = {path="../mvg", optional=true}
serialport = { version = "3.0.0", optional = true }
bytes = "1.0"
nalgebra = {version="0.26", optional = true }
opencv-ros-camera = "0.8"
alga = { version = "0.9", optional = true }
approx = { version = "0.4", optional = true }
rt-image-viewer = {path="../rt-image-viewer", optional=true}
opencv-calibrate = {path="../opencv-calibrate", optional=true}
camcal = {path="../camcal", optional=true}
posix-scheduler = { path = "../posix-scheduler", optional=true}
rust-cam-bui-types = {path="../rust-cam-bui-types"}
crossbeam-ok = {path="../crossbeam-ok"}
webm-writer = { path = "../webm-writer" }
strand-cam-csv-config-types = {path="../strand-cam-csv-config-types"}
plugin-defs = {path="../plugin-defs", optional=true}
bg-movie-writer = {path="../bg-movie-writer"}
strand-cam-pseudo-cal = {path="../strand-cam-pseudo-cal", optional=true}
nvenc = {path="../nvenc"}
ads-apriltag = {path="../apriltag", optional=true}

[build-dependencies]
bui-backend-codegen = {version="0.9", default-features = false}

[features]
default = ["image_tracker", "imtrack-absdiff", "cfg-pt-detect-src-prefs", "checkercal", "jemalloc"]

fiducial = ["ads-apriltag", "csv", "libflate"]

backtrace = []

send-bg-images-to-mainbrain = []

checkercal = ["strand-cam-storetype/checkercal", "opencv-calibrate", "camcal", "mvg"]

cfg-pt-detect-src-prefs = []

plugin-process-frame = ["plugin-defs"]
flydra-uds = ["image-tracker/flydra-uds"]

# Priority setting, high priority for camera threads, low priority for bg-image thread
posix_sched_fifo = ["posix-scheduler", "posix-scheduler/linux"]

# Serve style
# FIXME: temporarly remove "rt-image-viewer/bundle_files" from this list because it fails to build
# if "debug-images" is not enabled.
bundle_files = ["bui-backend/bundle_files", "bui-backend-codegen/bundle_files", "includedir", "phf" ]
serve_files = ["bui-backend/serve_files", "bui-backend-codegen/serve_files"]#, "rt-image-viewer/serve_files"]

# Backend choice
backend_dc1394 = ["ci2-dc1394"]
backend_flycap2 = ["ci2-flycap2"]
backend_pyloncxx = ["ci2-pyloncxx"]
# backend_aravis = ["ci2-aravis"]

# Tune defaults in image-tracker
imtrack-dark-circle = []
imtrack-absdiff = []

# Other features
with_camtrig = ["camtrig", "camtrig-comms", "serialport", "strand-cam-storetype/with_camtrig"]

flydratrax = ["mvg", "nalgebra", "strand-cam-pseudo-cal",
    "approx", "strand-cam-storetype/flydratrax", "alga",
    "flydra2", "flydra2/flat-3d", "flydra2/bundle_files", "image_tracker"]

start-object-detection = ["image_tracker"]
initially-unsychronized = []

# build with the image-tracker, which also requires IPP, fastimage, etc.
image_tracker = ["image-tracker"]

debug-images = ["image-tracker/debug-images", "rt-image-viewer"]

jemalloc = ["jemallocator"]
