[package]
name = "mvg-util"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]

[dependencies]
mvg = {path=".."}
flydra-mvg = {path="../../flydra-mvg"}
structopt = "0.3"
nalgebra = "0.26"
pretty-print-nalgebra = {git="https://github.com/strawlab/pretty-print-nalgebra", rev="142f427bfe9d2230b0dae0a5f7527703f43ae899"}
itertools = "0.8"
