[package]
name = "tracking"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
adskalman = "0.8"
nalgebra = "0.26"
num-traits = "0.2"

[dev-dependencies]
approx = "0.4"
