[package]
name = "flydra-mvg-fuzz-target"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = {version="0.8",optional=true}
flydra-mvg = {path=".."}
mvg = {path="../../mvg"}
nalgebra = "0.26"
anyhow = "1.0"
