[package]
name = "ci2-simple-async-demo"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
log = "0.4"
machine-vision-formats = { path = "../machine-vision-formats" }
timestamped-frame = { path = "../timestamped-frame" }
ci2 = { path = "../ci2" }
ci2-async = { path = "../ci2-async" }
chrono = "0.4"
env_logger = "0.8"
# ci2-aravis = { path = "../ci2-aravis", optional = true }
ci2-pyloncxx = { path = "../ci2-pyloncxx" }
ci2-flycap2 = { path = "../ci2-flycap2", optional = true }
ci2-dc1394 = { path = "../ci2-dc1394", optional = true }
futures = "0.3"
