[package]
name = "braid"
version = "0.9.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition="2018"
homepage = "https://strawlab.org/braid"

[dependencies]
configure = "0.1.1"
toml = "0.5"
serde = {version="1.0",features=["derive"]}
structopt = "0.3"
log = { version = "0.4", features = ["release_max_level_debug"] }
anyhow = "1.0"
dotenv = "0.13"
shellexpand = "2.0"
chrono = "0.4"
human-panic = "1.0.3"

env-tracing-logger = {path="../env-tracing-logger"}
flydra-types = {path="../flydra-types"}
image-tracker-types = {path = "../image-tracker/image-tracker-types"}
im-pt-detect-config = {path = "../image-tracker/im-pt-detect-config"}
