[package]
name = "image-tracker"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
thiserror = "1.0"
machine-vision-formats = { path = "../machine-vision-formats" }
timestamped-frame = {path="../timestamped-frame"}
basic-frame = {path="../basic-frame"}
num-traits = "0.2"
crossbeam-channel = "0.5"
thread-control = "0.1"
cast = "0.2.2"
serde = {version="1.0",features=["derive"]}
serde_json = { version = "1.0"}
serde_cbor = "0.9"
serde_yaml = "0.8"
tokio = {version="1.0.1", default-features=false, features=["rt"]}
stream-cancel = "0.8"
hyper = "0.14"
nalgebra = "0.26"
ncollide2d = "0.29"
fastimage = { version = "0.1", path = "../fastimage" }
ci2 = { path = "../ci2" }
ci2-remote-control = { path = "../ci2-remote-control" }
rust-cam-bui-types = {path="../rust-cam-bui-types" }
flydra-types = { path = "../flydra-types" }
rt-image-viewer = { version = "0.1", path = "../rt-image-viewer", optional = true }
ufmf = {path = "../ufmf"}
byteorder = "1.1"
chrono = "0.4"
unix_socket = {version="0.5", optional=true}
futures = "0.3"
clap = "2.20"
semver = {version = "0.9", features = ["serde"] }
mvg = {path="../mvg"}
image-tracker-types = {path="image-tracker-types", default-features = false}
http-video-streaming-types = {path="../http-video-streaming/http-video-streaming-types"}
datetime-conversion = {path="../datetime-conversion"}
posix-scheduler = {path="../posix-scheduler", optional=true}
bui-backend-session = {path="../bui-backend-session"}
crossbeam-ok = {path="../crossbeam-ok"}
ncollide-geom = {path="../ncollide-geom"}

[dev-dependencies]
fmf = { path = "../fmf" }
download-verify = {path="../download-verify"}
env_logger = "0.8"
im-pt-detect-config = {path = "im-pt-detect-config"}
ipp-sys = "0.4.4"
tokio = {version="1.0.1", default-features=false, features=["macros"]}

[features]
flydra-uds=["unix_socket"]

debug-images = ["rt-image-viewer"]

linux = ["posix-scheduler","posix-scheduler/linux"]
